### ISSUE TITLE
Getting started issues installing CocoaPods

### ISSUE THREAD

**Issue by dzuluaga** [apigee/IgniteEngine-iOS#148]
I was running into issues with instructions provided in the prerequisites section. This post help me to fix it.

http://stackoverflow.com/questions/24321534/pod-setup-cannot-find-cocoapods

**Comment by r3mus** [comment]
Which of the two answers worked for you?

**Comment by dzuluaga** [comment]
This one. http://stackoverflow.com/questions/24321534/pod-setup-cannot-find-cocoapods#answer-30199523
