### ISSUE TITLE
Loving Ignite Engine.......

### ISSUE THREAD

**Issue by MartinOrtiz** [apigee/IgniteEngine-iOS#157]
Only issue, coming from Windows side of fence...., why are we editing these text files manually?

What about a gui tool to do this? 

I may play around and make a WPF windows app that does this....since I'm more familiar with windows programming.

**Comment by r3mus** [comment]
Hey Martin - a GUI editor is definitely something we'd love to look at, but stability and features are our primary focus for now. Would love to see what you come up with in WPF though!
