### ISSUE TITLE
Datasource sort.key uncaught exception of type NSException

### ISSUE THREAD

**Issue by jeremyanticouni** [apigee/IgniteEngine-iOS#46]
When attempting to use sort.key and sort.order on an integer we crash. Works if you change the dataset to be a string instead of an integer, but that won't do. 

---

    2015-03-10 19:28:50.589 Ignite_iOS_Engine[28625:538865] -[__NSCFNumber localizedCaseInsensitiveCompare:]: unrecognized selector sent to instance 0xb000000000000013
    2015-03-10 19:28:50.592 Ignite_iOS_Engine[28625:538865] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber localizedCaseInsensitiveCompare:]: unrecognized selector sent to instance 0xb000000000000013'
    *** First throw call stack:
    (
      0   CoreFoundation                      0x000000010b207f35 __exceptionPreprocess + 165
      1   libobjc.A.dylib                     0x000000010aaf1bb7 objc_exception_throw + 45
      2   CoreFoundation                      0x000000010b20f04d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
      3   CoreFoundation                      0x000000010b16727c ___forwarding___ + 988
      4   CoreFoundation                      0x000000010b166e18 _CF_forwarding_prep_0 + 120
      5   Foundation                          0x000000010826788f _NSCompareObject + 49
      6   CoreFoundation                      0x000000010b124e5b __CFSimpleMergeSort + 171
      7   CoreFoundation                      0x000000010b124d73 CFSortIndexes + 547
      8   CoreFoundation                      0x000000010b15ffc0 CFMergeSortArray + 240
      9   Foundation                          0x00000001082672e3 _sortedObjectsUsingDescriptors + 593
      10  Foundation                          0x0000000108267039 -[NSArray(NSKeyValueSorting) sortedArrayUsingDescriptors:] + 525
      11  Ignite_iOS_Engine                   0x000000010665d9aa -[IXJSONDataProvider calculateAndStoreDataRowResultsForDataRowPath:] + 778
      12  Ignite_iOS_Engine                   0x000000010665f3f0 -[IXJSONDataProvider rowCount:] + 256
      13  Ignite_iOS_Engine                   0x000000010663f0a6 -[IXCellBasedControl reload] + 150
      14  Ignite_iOS_Engine                   0x0000000106625489 -[IXTable reload] + 57
      15  Ignite_iOS_Engine                   0x000000010663f7db -[IXCellBasedControl dataProviderDidUpdate:] + 91
      16  CoreFoundation                      0x000000010b1d7cec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
      17  CoreFoundation                      0x000000010b0d78a4 _CFXNotificationPost + 2484
      18  Foundation                          0x00000001082296b8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
      19  Ignite_iOS_Engine                   0x0000000106614ce2 __77-[IXBaseDataProvider fireLoadFinishedEvents:shouldCacheResponse:isFromCache:]_block_invoke + 98
      20  libdispatch.dylib                   0x000000010bf3bba6 _dispatch_call_block_and_release + 12
      21  libdispatch.dylib                   0x000000010bf597f4 _dispatch_client_callout + 8
      22  libdispatch.dylib                   0x000000010bf428fb _dispatch_main_queue_callback_4CF + 949
      23  CoreFoundation                      0x000000010b16ffe9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
      24  CoreFoundation                      0x000000010b132eeb __CFRunLoopRun + 2043
      25  CoreFoundation                      0x000000010b132486 CFRunLoopRunSpecific + 470
      26  GraphicsServices                    0x000000010d3e49f0 GSEventRunModal + 161
      27  UIKit                               0x0000000109542420 UIApplicationMain + 1282
      28  Ignite_iOS_Engine                   0x00000001065cef13 main + 115
      29  libdyld.dylib                       0x000000010bf8e145 start + 1
      30  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

---
Datasource JSON:

    {
        "_id": "cioPodcastsCache",
        "_type": "JSON",
        "actions": [
          {
            "_type": "Function",
            "attributes": {
              "_target": "episodesTable",
              "functionName": "pullToRefresh.end"
            },
            "on": "success"
          },
          {
            "_type": "Refresh",
            "attributes": {
              "_target": "podcastsTable"
            },
            "on": "success"
          },
          {
            "_type": "Alert",
            "attributes": {
              "message": "Status: [[$self.posts.0.status]]"
            },
            "enabled": false,
            "on": "success"
          }
        ],
        "attributes": {
          "baseUrl": "/new_data.json",
          "autoLoad.enabled": false,
          "cache.id": "cioPodcastsCache2",
          "predicate.format": "NOT(%K CONTAINS[c] %@)",
          "predicate.arguments": "status,unreleased",
          "sort.key":"episodeNumber",
          "sort.order":"descending",
          "http.method": "GET"
        }
      }

Dataset 1, crashes (numbers as integers):

    {
      "posts": [
        {
          "title": "Aneesh Chopra",
          "episodeNumber": 1
        },
        {
          "title": "Brian Lillie",
          "episodeNumber": 2
        }
      ]
    }

Dataset 2, works (numbers as strings):

    {
      "posts": [
        {
          "title": "Aneesh Chopra",
          "episodeNumber": "1"
        },
        {
          "title": "Brian Lillie",
          "episodeNumber": "2"
        }
      ]
    }

**Comment by r3mus** [comment]
Fixed in https://github.com/apigee/IgniteEngine-iOS/commit/122e578da0fb4a453781088a591eb08bc1639a79
