### ISSUE TITLE
TextInput needs a returnKeyPressed clears field

### ISSUE THREAD

**Issue by garazi** [apigee/IgniteEngine-iOS#75]
Need a new attribute for TextInput that would allow the field to be cleared when the Return Key is pressed. Currently you have to use the setText function to set the text of the input to an empty string.

**Comment by r3mus** [comment]
@garazi can accomplish this via Function `"setText": ""`. Eventually we'll migrate this to a Modify `"text": ""`. Is there any reason to keep this open or can we close it?

**Comment by garazi** [comment]
Yes, as mentioned, we can do it with either setText or text set to "", but I was thinking something like the dismissOnReturn.enabled could also be clearOnReturn.

**Comment by r3mus** [comment]
I think having it this way would break most UX-conventions. We might be better to implement this by enabling a clear/cancel icon inside the text field (as Mobile Safari's omnibar does).

**Comment by jeremyanticouni** [comment]
I think this is a non-issue, we already support clear/cancel icons:
```objc
IX_STATIC_CONST_STRING kIXRightImage = @"image.right"; // Must use full path within assets (aka "assets/images/image.png" ). Only works on non multiline input.
IX_STATIC_CONST_STRING kIXLeftImage = @"image.left"; // Must use full path within assets (aka "assets/images/image.png" ). Only works on non multiline input.
IX_STATIC_CONST_STRING kIXHidesImagesWhenEmpty = @"hideImageWhenEmpty.enabled"; // Only works on non multiline input.
```
